<?php
/*
 * This file is part of the Calculation package.
 *
 * Copyright (c) 2019 bibi.nu. All rights reserved.
 *
 * This computer code is protected by copyright law and international
 * treaties. Unauthorised reproduction or distribution of this code, or
 * any portion of it, may result in severe civil and criminal penalties,
 * and will be prosecuted to the maximum extent possible under the law.
 */

declare(strict_types=1);

namespace App\Twig;

use Twig\Extension\AbstractExtension;
use Twig\TwigFunction;

/**
 * Extension to generate CSP nonce key.
 *
 * @author Laurent Muller
 */
final class NonceExtension extends AbstractExtension
{
    /**
     *  The length of generated bytes.
     *
     *  @var int
     */
    private $length;

    /**
     *  The generated nonce.
     *
     *  @var string
     */
    private $nonce;

    /**
     * Constructor.
     *
     * @param int $length the length of generated bytes
     */
    public function __construct(int $length = 16)
    {
        $this->length = $length;
    }

    /**
     * {@inheritdoc}
     */
    public function getFunctions()
    {
        return [
            new TwigFunction('csp_nonce', [$this, 'getNonce']),
        ];
    }

    /**
     * Generates a random nonce parameter.
     */
    public function getNonce(): string
    {
        if (!$this->nonce) {
            $this->nonce = \bin2hex(\random_bytes($this->length));
        }

        return $this->nonce;
    }
}
