doctrine:
     orm:
         dql:
             datetime_functions:
                 date_format: DoctrineExtensions\Query\Mysql\DateFormat
                 day: DoctrineExtensions\Query\Mysql\Day
                 month: DoctrineExtensions\Query\Mysql\Month
                 week: DoctrineExtensions\Query\Mysql\Week
                 year: DoctrineExtensions\Query\Mysql\Year
             numeric_functions:
                 ceil: DoctrineExtensions\Query\Mysql\Ceil
                 floor: DoctrineExtensions\Query\Mysql\Floor
                 round: DoctrineExtensions\Query\Mysql\Round
             string_functions:
                 ifelse: DoctrineExtensions\Query\Mysql\IfElse
                 ifnull: DoctrineExtensions\Query\Mysql\IfNull
