framework:
    cache:
        # see https://symfony.com/doc/current/cache.html
        pools:
            # used by the App\Service\ApplicationService
            cache.app_service:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
            # used by the App\Service\UserService
            cache.user_service:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
