fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%mailer_user_email%'
        sender_name: '%mailer_user_name%'
    registration:
        confirmation:
            enabled: true
    profile:
        form:
            type: App\Form\FosUserProfileFormType
            name: ''
    change_password:
        form:
            type: App\Form\FosUserChangePasswordType
            name: ''
    resetting:
        form:
            type: App\Form\FosUserResettingFormType
            name: ''