framework:
    # global
    secret: '%app_secret%'
    http_method_override: true

    # session
    session:
        enabled: true
        cookie_secure: true
        cookie_httponly: true
        cookie_samesite: 'lax'
        cookie_path: '%cookie_path%'
        storage_factory_id: session.storage.factory.native

    # edition
    ide: phpstorm

    # errors
    php_errors:
        log: true

    # see https://symfony.com/doc/current/forms.html#form-validation-messages
    form:
        legacy_error_messages: false

    #assets:
    #    base_urls: '%asset_base%'
