framework:
    # global
    secret: '%app_secret%'

    # session
    session:
        cookie_path: '%cookie_path%'
        cookie_samesite: lax
        cookie_secure: 'auto'
        storage_factory_id: session.storage.factory.native

    # errors
    php_errors:
        log: true

    # see https://symfony.com/doc/current/forms.html#form-validation-messages
    form:
        legacy_error_messages: false

    # assets
    assets:
        base_urls: '%asset_base%'
        packages:
            local:
                base_urls: '%asset_locale%'
