framework:
    # global
    secret: '%app_secret%'
    http_method_override: true
    handle_all_throwables: true

    # session
    session:
        enabled: true
        handler_id: null
        cookie_secure: true
        cookie_samesite: 'lax'
        cookie_path: '%cookie_path%'

    # assets
    assets:
        version_strategy: 'App\Service\AssetVersionService'

    # router
    router:
        utf8: true

    # errors
    php_errors:
        log: true

    # form
    form:
        csrf_protection:
            field_name: token
