security:
    enable_authenticator_manager: true

    encoders:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            switch_user: true
            custom_authenticator: App\Security\LoginFormAuthenticator

            logout:
                path: app_logout
                invalidate_session: false

            remember_me:
                remember_me_parameter: remember_me                 
                secret: '%app_secret%'
                path:   '%cookie_path%'
                secure: false

    access_control:
        - { path: ^/login,                 roles: PUBLIC_ACCESS  }
        - { path: ^/resetting,             roles: PUBLIC_ACCESS  }
        - { path: ^/reset-password,        roles: PUBLIC_ACCESS  }
        #- { path: ^/register$,             roles: PUBLIC_ACCESS  }
        - { path: ^/about/policy,          roles: PUBLIC_ACCESS  }
        - { path: ^/about/licence,         roles: PUBLIC_ACCESS  }
        - { path: ^/ajax/checkexist,       roles: PUBLIC_ACCESS  }
        - { path: ^/ajax/captcha/image,    roles: PUBLIC_ACCESS  }
        - { path: ^/ajax/captcha/validate, roles: PUBLIC_ACCESS  }
        - { path: ^/admin/,                roles: ROLE_ADMIN }
        - { path: ^/,                      roles: ROLE_USER }
