vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: '/images/users'
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer:
                service: App\Service\UserNamer
