risky: true
version: 8.3
preset: symfony2025
monolithic: true
finder:
  exclude:
    - "vendor"
  name: "*.php"
enabled:
  - native_function_invocation
  - concat_with_spaces
disabled:
  - no_nullable_type_declarations
  - native_function_invocation_symfony
  - concat_without_spaces
  - phpdoc_to_comment
  - function_declaration
  - symfony_braces
