language: php

php:
  - 7.4
  
env:
  - SYMFONY_VERSION=5.0.*
  
before_install:
  - composer self-update
  - composer validate
    
install:    
  - flags="--prefer-dist --optimize-autoloader --no-dev --no-progress --no-interaction"
  - composer install $flags
  - bin/composer install $flags  
