dist: xenial
language: php

os: 
  - linux
    
php:
  - 7.4
      
env:
  - SYMFONY_VERSION=5.1.*
  
before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer validate
    
install:    
  - flags="--prefer-dist --no-progress --no-interaction"
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install $flags

notifications:  
  # slack: haslerrail:bmYUu3l0jnDbU5DZVrbmvivZ
  slack: "${{ secrets.SLACK_KEY }}"

