monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels:
            - '!event'
            formatter: monolog.custom_formatter
        console:
            type: console
            process_psr_3_messages: false
            channels:
            - '!event'
            - '!doctrine'
            - '!console'
        deprecation:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            formatter: monolog.custom_formatter
            channels:
            - php
        #mailer_error:
        #    type: native_mailer
        #    from_email: calculation@bibi.nu
        #    to_email: calculation@bibi.nu
        #    subject: Exception %%message%%
        #    channels:
        #    - app
