monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
            formatter: monolog.custom_formatter
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        deprecation:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.deprecations.log'
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            formatter: monolog.custom_formatter
            channels: ['php']
        #symfony_mailer:
            #type: symfony_mailer
            #from_email: '%env(string:MAILER_EMAIL)%'
            #to_email: '%env(string:MAILER_EMAIL)%'
            #subject: Une erreur s’est produite : %%message%%
            #level: debug
            #formatter: monolog.formatter.html
            #content_type: text/html
