fos_user_profile_edit:
    path: /profile/edit
    defaults:
        _controller: fos_user.profile.controller:editAction
fos_user_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'
    prefix: /profile
fos_user_security:
    resource: '@FOSUserBundle/Resources/config/routing/security.xml'
fos_user_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'
    prefix: /resetting
fos_user_resetting_request:
    path: /resetting/request
    defaults:
        _controller: App\Controller\SecurityController:requestAction
#fos_user_register:
#    resource: '@FOSUserBundle/Resources/config/routing/registration.xml'
#    prefix: /register
