# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # fixed
    locale:             fr_CH
    app_name:           Calculation
    app_version:        1.5.18
    app_owner:          bibi.nu
    app_owner_url:      https://www.bibi.nu
    app_owner_city:     Montévraz
    app_description:    Programme de calculation.

    app_secret:         '%env(APP_SECRET)%'
    app_environment:    '%env(APP_ENVIRONMENT)%'

    # mailer
    mailer_user_name: Calculation
    mailer_user_email: calculation@bibi.nu

    # assets
    asset_base: '%env(ASSET_BASE)%'
    asset_locale: '%env(ASSET_LOCALE)%'

    # cookies
    cookie_path: '%env(COOKIE_PATH)%'
    cookie_secure: '%env(bool:COOKIE_SECURE)%'
    cookie_same_site: '%env(COOKIE_SAME_SITE)%'

    # keys
    openweather_key: '%env(OPENWEATHER_KEY)%'
    bing_translator_key:   '%env(BING_TRANSLATOR_KEY)%'
    google_translator_key: '%env(GOOGLE_TRANSLATOR_KEY)%'
    yandex_translator_key: '%env(YANDEX_TRANSLATOR_KEY)%'

    google_recaptcha_secret: '%env(GOOGLE_RECAPTCHA_SECRET)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

    #links
    link_dev: '%env(LINK_DEV)%'
    link_prod: '%env(LINK_PROD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $appName: '%app_name%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # App\Listener\PersistenceListener:
    #     tags:
    #         - { name: 'doctrine.event_subscriber' }

    # make public to use with vich_uploader
    App\Service\UserNamer:
        public: true

    # validators
    App\Validator\RecaptchaValidator:
        arguments: ['%google_recaptcha_secret%']

    # datatables
    App\DataTable\:
        resource: '../src/DataTable/'
        exclude:  '../src/DataTable/Model'
        tags: [datatable]

    # used to update calculation when groups or items change
    App\Listener\CalculationListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush}

    # used to update TimestampableInterface
    App\Listener\TimestampableListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush}

    # custom line formatter for monolog
    monolog.custom_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments: ["%%datetime%%|%%channel%%|%%level_name%%|%%message%%|%%context%%|%%extra%%\n", "d.m.Y H:i:s"]

    # custom AppVariable
    twig.app_variable:
        class: App\Service\ApplicationService
        public: false
        calls:
            - [setEnvironment, ["%kernel.environment%"]]
            - [setDebug, ["%kernel.debug%"]]
            - [setTokenStorage, ['@security.token_storage']]
            - [setRequestStack, ['@request_stack']]
