# Put parameters here that don't need to change on each machine where the application is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # fixed
    locale:             fr_CH
    app_name:           Calculation
    app_version:        2.4.0
    app_owner:          bibi.nu
    app_owner_url:      https://www.bibi.nu
    app_owner_city:     Montévraz
    app_description:    Programme de calculation.

    app_secret:         '%env(string:APP_SECRET)%'
    app_mode:           '%env(string:APP_MODE)%'

    # mailer
    mailer_user_name: Calculation
    mailer_user_email: calculation@bibi.nu

    # cookies
    cookie_path: '%env(string:COOKIE_PATH)%'

    # keys
    akismet_key: '%env(string:AKISMET_KEY)%'
    ip_stack_key: '%env(string:IP_STACK_KEY)%'
    open_weather_key: '%env(string:OPEN_WEATHER_KEY)%'
    exchange_rate_key: '%env(string:EXCHANGE_RATE_KEY)%'
    bing_translator_key:   '%env(string:BING_TRANSLATOR_KEY)%'
    google_translator_key: '%env(string:GOOGLE_TRANSLATOR_KEY)%'
    google_recaptcha_secret_key: '%env(string:GOOGLE_RECAPTCHA_SECRET_KEY)%'
    google_recaptcha_site_key: '%env(string:GOOGLE_RECAPTCHA_SITE_KEY)%'

    #links
    link_dev: '%env(string:LINK_DEV)%'
    link_prod: '%env(string:LINK_PROD)%'

    # optimize
    container.dumper.inline_factories: true

services:
    # default configuration for services
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Twig\Extra\Markdown\MarkdownInterface $markdown: '@twig.markdown.default'

    # make classes in src/ available to be used as services
    App\:
        resource: '../src/*'
        exclude:
            - '../src/Entity'
            - '../src/Enums'
            - '../src/Faker'
            - '../src/Migrations'
            - '../src/Pdf'
            - '../src/Report'
            - '../src/Spreadsheet'
            - '../src/Tests'
            - '../src/Traits'
            - '../src/Kernel.php'

    # make public to use with vich_uploader
    App\Service\UserNamer:
        public: true

    # used to display flash message when entities change
    #    App\Listener\PersistenceListener:
    #        tags:
    #            - { name: 'doctrine.event_subscriber', event: 'postPersist', lazy: true, entity: 'App\Entity\AbstractEntity' }
    #            - { name: 'doctrine.event_subscriber', event: 'postRemove', lazy: true, entity: 'App\Entity\AbstractEntity' }
    #            - { name: 'doctrine.event_subscriber', event: 'postUpdate', lazy: true, entity: 'App\Entity\AbstractEntity' }

    # used to update TimestampableInterface
    App\Listener\TimestampableListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'onFlush', lazy: true, entity: 'App\Interfaces\TimestampableInterface' }
            - { name: 'doctrine.event_listener', event: 'onFlush', lazy: true, entity: 'App\Interfaces\ParentTimestampableInterface' }

    # custom line formatter for monolog
    monolog.custom_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments: ["%%datetime%%|%%channel%%|%%level_name%%|%%message%%|%%context%%|%%extra%%\n", "d.m.Y H:i:s"]
