---
title: Timestampable Trait
---
classDiagram
    direction TB

    class TimestampableInterface {
        <<Interface>>
    }

    class TimestampableTrait {
        <<Trait>>
        -?DatePoint createdAt
        -?string createdBy
        -?DatePoint updatedAt
        -?string $updatedBy
        +getCreatedAt() ?DatePoint
        +getCreatedBy() ?string
        +getCreatedMessage(bool short) TranslatableMessage
        +getUpdatedAt() ?DatePoint
        +getUpdatedBy() ?string
        +getUpdatedMessage(bool short) TranslatableMessage
        +updateTimestampable(DatePoint date, string user) bool
    }

    TimestampableInterface <|.. TimestampableTrait

    click TimestampableInterface call nodeCallback()
