---
title: Calculation State
---

classDiagram
    direction LR

    class CalculationState {
        -string code
        -string color
        -bool editable
        -string description
        -Collection~Calculation~ calculations
        +getCode() string
        +setCode(string)
        +getColor() string
        +setColor(string)
        +isEditable() bool
        +setEditable(bool)
        +getDescription() string
        +setDescription(string)
        +getCalculations() Collection~calculations~
        +count() int
    }

    class Calculation {
    }

    CalculationState "0" --> "*" Calculation

    click Calculation call nodeCallback()
