name: CI

on: [ push, pull_request ]

jobs:
    php-cs-fixer:
        uses: laurentmuller/.github/.github/workflows/php-cs-fixer.yaml@main

    phpstan:
        uses: laurentmuller/.github/.github/workflows/phpstan.yaml@main

    rector:
        uses: laurentmuller/.github/.github/workflows/rector.yaml@main

    twig-cs-fixer:
        uses: laurentmuller/.github/.github/workflows/twig-cs-fixer.yaml@main

    validate-composer:
        uses: laurentmuller/.github/.github/workflows/validate-composer.yaml@main

    validate-container:
        uses: laurentmuller/.github/.github/workflows/validate-container.yaml@main

    validate-translation:
        uses: laurentmuller/.github/.github/workflows/validate-translation.yaml@main

    validate-markdown:
        uses: laurentmuller/.github/.github/workflows/validate-markdown.yaml@main

    validate-twig:
        uses: laurentmuller/.github/.github/workflows/validate-twig.yaml@main

    validate-yaml:
        uses: laurentmuller/.github/.github/workflows/validate-yaml.yaml@main
