name: Composer Diff

on:
    push:
        paths:
            - 'composer.lock'
    pull_request:
        paths:
            - 'composer.lock'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Generate composer diff
                id: composer_diff
                uses: IonBazan/composer-diff-action@v1

            -   uses: marocchino/sticky-pull-request-comment@v2
                if: ${{ steps.composer_diff.outputs.composer_diff_exit_code != 0 }}
                with:
                    header: composer-diff
                    message: |
                        <details>
                        <summary>Composer package changes</summary>
                        
                        ${{ steps.composer_diff.outputs.composer_diff }}
                        
                        </details>
