name: Markdown Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v11
        with:
          globs: '*.md'
