name: Static analysis

on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan with PHP 7.4
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: intl
          php-version: '7.4'
          tools: composer:v2

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: composer-${{ runner.os }}-${{ hashFiles('composer.*') }}
          restore-keys: composer-${{ runner.os }}-composer-

      - name: Download dependencies
        run: |
          composer update --no-interaction --no-progress --optimize-autoloader
          composer bin phpstan install --no-interaction --no-progress --optimize-autoloader

      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyze --no-progress

