name: Psalm

on: [ push, pull_request ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Install PHP with extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    coverage: none

            -   name: Install dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Install Psalm
                working-directory: ./vendor-bin/psalm
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Run Psalm
                run: vendor-bin/psalm/vendor/bin/psalm --config=psalm.xml --no-progress
