name: Twigcs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: intl
          php-version: '8.1'
          tools: composer:v2

      - name: Determine composer cache directory
        id: composer-cache
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: Cache dependencies installed with composer
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.directory }}
          key: composer-${{ runner.os }}-${{ hashFiles('composer.*') }}
          restore-keys: composer-${{ runner.os }}-composer-

      - name: Download dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          composer bin twigcs install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-source

      - name: Run Twigcs
        run: vendor/bin/twigcs /templates --severity error --display blocking
