name: Unit Tests

on: [push, pull_request]

jobs:
  symfony:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: ext-xsl,xsl,sqlite3,pdo_sqlite,intl

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        env: 
          COMPOSER_MEMORY_LIMIT: -1

      - name: Validate Composer
        run: composer validate

      - name: Run Tests
        run: php bin/phpunit
